//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APK_IDE {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class SettingsAPP : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsAPP defaultInstance = ((SettingsAPP)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsAPP())));
        
        public static SettingsAPP Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NULL")]
        public string DnSpyDir {
            get {
                return ((string)(this["DnSpyDir"]));
            }
            set {
                this["DnSpyDir"] = value;
            }
        }
    }
}
